### ISSUE TITLE
Reconcile OMLT version between IDAES and dispatches

### ISSUE THREAD

**Issue by Xinhe-Chen** [gmlc-dispatches/dispatches#149]
IDAES now requires OMLT v0.3.1 for installation.
https://github.com/IDAES/idaes-pse/blob/main/setup.py#L85

For building the surrogates, we use OMLT v1.0, which is the latest version available. 

@ksbeattie @lbianchi-lbl will IDAES update to OMLT v1.0 in the new 2.0 release? We don't want to have a conflict that dispatches use OMLT v1.0 while IDAES uses OMLT v0.3.1.

**Comment by Xinhe-Chen** [comment]
Update
* May not need to use NN surrogates depending on the latest parameter sweeps.

**Comment by jsiirola** [comment]
OK - I just spent a little time looking at this.  There are a couple issues with moving to OMLT 1.0 that we need to work through:
- OMLT 1.0 made a pretty substantial change to their model: they now *always* create their own list of input / output variables.  In the 0.3.1 version, we could pass in lists of Var objects that OMLT should use to generate the model.  I think we can migrate IDAES over to using the 1.0 format, but that would require rewriting a large chunk of `build_model()` in `KerasSurrogate`.  Ugly, but not impossible.
- OMLT has a potentially incomplete dependency list: In order to import / use `load_keras_sequential`, we need to install `onnx` (technically an optional testing dependency).  This has been reported upstream (cog-imperial/OMLT#96), but until it is resolved, we will need to add an `onnx` dependency to IDAES / DISPATCHES.

**Comment by ksbeattie** [comment]
@jsiirola & @adowling2 we should decide how pressing this is for the Dec release of DISPATCHES.

**Comment by ksbeattie** [comment]
@rundxdi, is working on this.

**Comment by rundxdi** [comment]
Draft PR has been submitted to IDAES to resolve this issue; see [https://github.com/IDAES/idaes-pse/issues/982](url) for more details

**Comment by ksbeattie** [comment]
@Xinhe-Chen will check that OMLT 1.0 (what DISPATCHES uses) is compatible with 1.1 (what IDAES has)
