### ISSUE TITLE
Review and simplify documentation auto-generation directives

### ISSUE THREAD

**Issue by lbianchi-lbl** [gmlc-dispatches/dispatches#72]
This was originally prompted while reviewing #57, but it's more of a cross-cutting concern involving the entire project's documentation.

Currently, there seem to be multiple types of auto-generation Sphinx directives used in the documentation: `module`, `automodule`, `autoclass`... It would be good to review how these are used in the current version of the docs, and ultimately come up with a consistent recommendations on which directive(s) should be used going forward.

**Comment by andrewlee94** [comment]
In short, you should be documenting the thing the user will use, i.e. the class or method. That being the case, `autoclass` or `automethod` would generally be the more appropriate thing to add to the docs.

For things like flowsheets, this will mean the developers need to think carefully about how they build and run the model so that it is amenable to documentation.
